### ISSUE TITLE
Trybuild constructs a Cargo.toml that fails to resolve transitive dependencies when said dependencies are used in a macro

### ISSUE THREAD

**Issue by ripdajacker** [dtolnay/trybuild#145]
Hey everyone

First of all thanks for creating this piece of software.

I am working on a project that uses macros to generate some code with `#[cfg(feature = "...")]` sprinkled here and there. 
It seems I have stumbled upon a corner-case of a bug that fails to compile code that uses said generated code.

There are two crates in play. The first one `dependency_a` is a `proc_macro` the other, `dependency_b` just a lib. 
`dependency_a` generates code that depends on a feature `foo` in `dependency_b`. Both crates have the same feature.

Attached is a zip containing a test that **should** compile but does not: 
[trybuil-transitive.zip](https://github.com/dtolnay/trybuild/files/7937837/trybuil-transitive.zip)

List of files:
```text
├── dependency-a
│   ├── Cargo.toml
│   ├── src
│   │   └── lib.rs
│   └── tests
│       └── fail.rs
└── dependency-b
    ├── Cargo.toml
    └── src
        └── lib.rs
```

dependency-a/Cargo.toml:
```toml
[package]
name = "dependency_a"
version = "0.1.0"
edition = "2021"

[features]
foo = ["dependency_b/foo"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
dependency_b = { path = "../dependency-b" }

[dev-dependencies]
#trybuild = { git = "https://github.com/ripdajacker/trybuild.git", branch = "transitive_features" }
trybuild = "1.0"
```

dependency-a/src/lib.rs:
```rust
// omitted use 

#[proc_macro_attribute]
pub fn my_macro(_attrs: TokenStream, _input: TokenStream) -> TokenStream {
    let  result: TokenStream2 = quote! {
        #[cfg(feature = "foo")]
        pub fn created_function() {
            dependency_b::run_this_b();
        }
    };

    result.into()
}

#[cfg(test)]
mod test {
    #[test]
    pub fn trybuild() {
        let t = trybuild::TestCases::new();
        t.pass("tests/fail.rs");
    }
}
```

dependency-a/tests/fail.rs:
```rust
use dependency_a::my_macro;

/// This generates `created_function` if the `foo` feature is set on `dependency_b`.
#[my_macro]
pub fn generate() {}

pub fn main() {
    created_function();
}
```

dependency-b/Cargo.toml:
```toml
[package]
name = "dependency_b"
version = "0.1.0"
edition = "2021"

[features]
foo = []

[lib]

[dependencies]
```

dependency-b/src/lib.rs:
```rust
#[cfg(feature = "foo")]
pub fn run_this_b() {}
```

**Comment by dtolnay** [comment]
I think this is behaving correctly according to the intended behavior of the v2 resolver in Cargo. `dependency-a/tests/fail.rs` is treated as if it were some other crate depending on `dependency_a`, the crate being tested, because the point of trybuild is to test the experience of downstream crates using your crate. When you run `cargo test --features foo`, the ui test is built as if it were a crate declaring a dependency on `dependency_a/foo`. If a crate did that, they'd get exactly the build failure that trybuild is showing in this case, because they'd be getting a host-dependency on `dependency_a` and `dependency_a/foo`, which introduces a host-dependency on `dependency_b/foo`, but they wouldn't have a target-dependency on `dependency_b/foo`.

To get a target-dependency on `dependency_b/foo` the downstream crate would need to add `dependency_b = { features = ["foo"] }`, which you can reproduce in your trybuild tests by adding:

```toml
[dev-dependencies]
dependency_b = { path = "../dependency-b", features = ["foo"] }
```
