### ISSUE TITLE
Tests panic when debugging from WSL2

### ISSUE THREAD

**Issue by adrianbenavides** [dtolnay/trybuild#153]
When I run the project's tests without the debugger it all seems to work just fine. But when I enable the debugger, I get the following error (note the `Cargo.toml` path it's trying to read from):

```rust
/home/adri/projects/opensource/trybuild/target/debug/deps/test-540c279f974d2fbc test --format=json --exact -Z unstable-options --show-output
error: failed to load manifest for dependency `trybuild`

Caused by:
  failed to read `/home/adri/projects/opensource/trybuild/target/tests/trybuild/\\wsl$\Ubuntu\home\adri\projects\opensource\trybuild/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

tests failed
thread 'test' panicked at 'tests failed', src/run.rs:52:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:525:12
   1: trybuild::run::<impl trybuild::Runner>::run::{{closure}}
             at ./src/run.rs:52:13
   2: core::result::Result<T,E>::unwrap_or_else
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1369:23
   3: trybuild::run::<impl trybuild::Runner>::run
             at ./src/run.rs:44:32
   4: <trybuild::TestCases as core::ops::drop::Drop>::drop
             at ./src/lib.rs:308:13
   5: core::ptr::drop_in_place<trybuild::TestCases>
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ptr/mod.rs:188:1
   6: test::test
             at ./tests/test.rs:22:1
   7: test::test::{{closure}}
             at ./tests/test.rs:2:1
   8: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Not sure if it's related but the generated paths from `target/tests/trybuild/Cargo.toml` also seems broken:

```toml
[package]
name = "trybuild-tests"
version = "0.0.0"
edition = "2018"
publish = false
[dependencies.trybuild]
path = "\\\\wsl$\\Ubuntu\\home\\adri\\projects\\opensource\\trybuild/"
default-features = false

[[bin]]
name = "trybuild-tests"
path = "main.rs"

[[bin]]
name = "trybuild000"
path = "\\\\wsl$\\Ubuntu\\home\\adri\\projects\\opensource\\trybuild/tests/ui/run-pass-0.rs"

[[bin]]
name = "trybuild001"
path = "\\\\wsl$\\Ubuntu\\home\\adri\\projects\\opensource\\trybuild/tests/ui/print-stdout.rs"

...
```

## Notes
- I know it makes no sense to use the debugger when running `trybuild`'s tests, but I thought it may be helpful to look into this.
- I'm on Windows 11 with WSL, using Clion 2021.3.3 [as described here](https://www.jetbrains.com/help/clion/how-to-use-wsl-development-environment-in-product.html)
