### ISSUE TITLE
Error 'unresolved import' when running from workspace

### ISSUE THREAD

**Issue by regexident** [dtolnay/trybuild#16]
I'm still seeing the same error …

```
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0432]: unresolved import `foo::Bar`
 --> $DIR/import_foo.rs:5:5
  |
5 | use foo::Bar
  |     ^^^^^^^^^^^^^^ no `Bar` in the root
```

… as reported in [this issue](https://github.com/dtolnay/trybuild/issues/1) (which seems to have been fixed around 1.0.4) when running from a workspace's member `foo-macros` importing a sibling `foo`. 😕

📦 A minimal reproduction sample project: [foo.zip](https://github.com/dtolnay/trybuild/files/3293220/foo.zip)

<details>
<summary>📜 Relevant sample code</summary>

`/Cargo.toml`:
```toml
[workspace]

members = [
    "foo-macros",
    "foo"
]

[patch.crates-io]
foo = { path = "foo" }
```

`/foo/Cargo.toml`:
```toml
[package]
name = "foo"
version = "0.0.0"
edition = "2018"
```

`/foo/src/lib.rs`:
```rust
#[derive(Debug)]
pub struct Bar;
```

`/foo-macros/Cargo.toml`:
```toml
[package]
name = "foo-macros"
version = "0.0.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "^0.15"

[dev-dependencies]
foo = "0.0.0"
trybuild = "^1.0"
```

`/foo-macros/examples/import.rs`:
```rust
#[macro_use]
extern crate foo_macros;
extern crate foo;

use foo::Bar;

foo!(
    #[allow(dead_code)]
    struct Dummy;
);

fn main() {
    println!("{:?}", Bar);
}
```

`/foo-macros/src/lib.rs`:
```rust
extern crate proc_macro;

#[proc_macro]
pub fn foo(input: proc_macro::TokenStream) -> syn::export::TokenStream {
    input
}
```

`/foo-macros/tests/compile_test.rs`:
```rust
#[test]
fn ui() {
    let t = trybuild::TestCases::new();
    t.pass("examples/import.rs");
}
```
</details>

If you run …

    $ cargo build --example import

… within the sample project you should get a successful compilation.

However running the same code as test (via `t.pass("examples/import.rs");`) …

    $ cargo test --test compile_test

you get …

```
Testing examples/import.rs ... error
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
error[E0432]: unresolved import `foo::Bar`
 --> $DIR/import.rs:5:5
  |
5 | use foo::Bar;
  |     ^^^^^^^^ no `Bar` in the root

For more information about this error, try `rustc --explain E0432`.
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```
