### ISSUE TITLE
Support target-specific dev dependencies

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/trybuild#5]
If the workspace's root Cargo.toml contains a section like the following, we will need to propagate that into the generated Cargo.toml through which we build the test cases.

```toml
[target.'cfg(unix)'.dev-dependencies]
libc = "0.2"
```
